name = "cafeelgato-geo-block"
main = "worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "cafeelgato-geo-block"
routes = [
  { pattern = "cafeelgato.com/*", zone_name = "cafeelgato.com" },
  { pattern = "www.cafeelgato.com/*", zone_name = "cafeelgato.com" }
]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
